[package]
name = "meta-maxim/luau-type-parser"
version = "1.1.3"
license = "MIT"
authors = ["Maxim Borsch <@Meta_Maxim>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
LuauTypes = "meta-maxim/luau-types@^1"